apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: sqs-prometheus-exporter

build:
  artifacts:
    - image: sqs-prometheus-exporter

deploy:
  helm:
    releases:
      - name: localstack
        remoteChart: https://github.com/localstack/helm-charts/releases/download/localstack-0.6.16/localstack-0.6.16.tgz
        namespace: monitoring
        createNamespace: true
        setValues:
          extraEnvVars:
            - name: SERVICES
              value: "sqs"
          enableStartupScripts: true
          # language=sh
          startupScriptContent: |
            #!/bin/bash
            echo "Creating SQS queue..."
            awslocal sqs create-queue --queue-name sample-queue
            url="http://sqs.us-east-1.localhost.localstack.cloud:4566/000000000000/sample-queue"
            for i in {1..100}; do
            awslocal sqs send-message --queue-url "$url" --message-body "Msg $i - $(date +%s)"
            echo "Sent message $i"
            done

      - name: kube-prometheus-stack
        remoteChart: https://github.com/prometheus-community/helm-charts/releases/download/kube-prometheus-stack-61.9.0/kube-prometheus-stack-61.9.0.tgz
        namespace: monitoring
        createNamespace: true
        setValues:
          defaultRules:
            create: true
            rules:
              etcd: false
              kubeScheduler: false
          alertmanager:
            enabled: false
          grafana:
            enabled: false
          kubeControllerManager:
            enabled: false
          kubeEtcd:
            enabled: false
          kubeScheduler:
            enabled: false

      - name: sqs-prometheus-exporter
        chartPath: chart/sqs-prometheus-exporter
        namespace: monitoring
        createNamespace: true
        setValueTemplates:
          image:
            repository: "{{.IMAGE_REPO_sqs_prometheus_exporter}}"
            tag: "{{.IMAGE_TAG_sqs_prometheus_exporter}}@{{.IMAGE_DIGEST_sqs_prometheus_exporter}}"
          sqs:
            region: us-east-1
            queueUrls: [ "http://sqs.us-east-1.localhost.localstack.cloud:4566/000000000000/sample-queue" ]
          deployment:
            extraEnv:
              AWS_ACCESS_KEY_ID: 123
              AWS_SECRET_KEY: fake123
              AWS_ENDPOINT_URL: http://localstack.monitoring.svc.cluster.local:4566

portForward:
  - resourceType: service
    resourceName: kube-prometheus-stack-prometheus
    namespace: monitoring
    port: 9090
    localPort: 9090
  - resourceType: service
    resourceName: localstack
    namespace: monitoring
    port: 4566
    localPort: 4566
  - resourceType: deployment
    resourceName: sqs-prometheus-exporter
    namespace: monitoring
    port: 8080
    localPort: 8080
