app:
  name: sqs-prometheus-exporter

image:
  repository: ghcr.io/jmriebold/sqs-prometheus-exporter
  # Defaults to appVersion in Chart.yaml
  tag: ""

deployment:
  resources:
    requests:
      memory: 15Mi
    limits: {}

  port: 8080

  podAnnotations: {}
  extraEnv: {}

  tolerations: []
  nodeSelector: {}
  affinity: {}

serviceAccount:
  name: ""
  create: false
  annotations: {}

sqs:
  region: us-west-2
  queueUrls: []
  monitorIntervalSeconds: 30
