app:
  name: sqs-prometheus-exporter

image:
  repository: jmriebold/sqs-prometheus-exporter
  tag: 1.0.5

deployment:
  resources:
    requests:
      memory: 15Mi
    limits: {}

  port: 8080

  podAnnotations: {}
  extraEnv: {}

  tolerations: []
  nodeSelector: {}
  affinity: {}

serviceAccount:
  name: ""
  create: false
  annotations: {}

sqs:
  region: us-west-2
  queueUrls: []
  monitorIntervalSeconds: 30
