app:
  name: sqs-prometheus-exporter

image:
  repository: ghcr.io/jmriebold/sqs-prometheus-exporter
  # Defaults to appVersion in Chart.yaml
  tag: ""

deployment:
  resources:
    requests:
      memory: 15Mi
    limits: {}

  port: 8080

  podAnnotations: {}
  extraEnv: {}

  tolerations: []
  nodeSelector: {}
  affinity: {}

serviceAccount:
  name: ""
  create: false
  annotations: {}

podMonitor:
  # Enable Prometheus metrics scraping
  enabled: true
  interval: 30s
  labels:
    # Must match Prometheus PodMonitor selector
    release: kube-prometheus-stack
  relabelings: []
  metricRelabelings: []
  targetLabels: []

sqs:
  region: us-west-2
  queueUrls: []
  monitorIntervalSeconds: 30
