name: Release chart

on:
  push:
    # Pseudo-enforce version change in Chart.yaml
    paths:
      - chart/sqs-prometheus-exporter/Chart.yaml

jobs:
  release-chart:
    name: Release chart

    runs-on: ubuntu-latest

    permissions:
      contents: write # to push chart release and create a release (helm/chart-releaser-action)
      packages: write # needed for ghcr access
      id-token: write # needed for keyless signing

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Fetch
        run: git fetch --prune --unshallow

      - name: Configure Git
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.9.2

      - name: Set up cosign-installer
        uses: sigstore/cosign-installer@v3

      - name: Log in
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Release
        env:
          REPO_NAME: ${{ github.event.repository.name }}
        run: |
          cd chart
          helm package ${REPO_NAME}
          helm push *.tgz "oci://ghcr.io/${GITHUB_REPOSITORY_OWNER}/charts"
